package com.dimstyl.dietitianhub.utilities;

import lombok.experimental.UtilityClass;

import java.time.LocalDate;

@UtilityClass
public class RegistrationUtil {
    public static String generateUsername(String firstName, String lastName, LocalDate dateOfBirth) {
        /*
        - This code snippet demonstrates the basic principle of username generation using the client's
        first name, last name and year of birth. Additional logic would be required for real-world use,
        including handling username conflicts.
        - username is generated by combining the firstName, LastName and the last 2 digits of the
        client's year of birth.
        */
        String fn = firstName.toLowerCase();
        String ln = lastName.substring(0, 1).toUpperCase() + lastName.substring(1).toLowerCase();
        String dob = String.valueOf(dateOfBirth.getYear()).substring(2);
        return fn + ln + dob;
    }
}
