services:
  postgres:
    container_name: postgres-dietitianHub
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clientDietitian_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialize the database with the following scripts
      - ../sql-scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ../sql-scripts/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/postgres-data/dietitianHub