services:
  postgres:
    container_name: postgres-dietitianHub
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clientDietitian_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialize the database with the scripts in the sql-scripts directory
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/postgres-data/dietitianHub