package gr.unipi.thesis.dimstyl.ui.helpers

enum class ContentType {

    MODAL_DRAWER_SHEET_TITLE, MODAL_DRAWER_SHEET_NAV_ITEMS,

    PROFILE_TEXT_INPUT_FIELD, PROFILE_GENDER_DOB_INPUT_FIELDS, PROFILE_BUTTONS,

    ANNOUNCEMENTS_SECTION_TITLE, ANNOUNCEMENTS_SECTION_BODY, ANNOUNCEMENTS_SECTION_CARD,
    NO_ANNOUNCEMENTS,

    ARTICLES, NO_ARTICLES,

    TABLE_HEADER, TABLE_BODY_ROW,

    SCHEDULED_APPOINTMENTS_TABLE, PENDING_APPOINTMENTS_TABLE, COMPLETED_APPOINTMENTS_TABLE,
    DECLINED_APPOINTMENTS_TABLE, CANCELLED_APPOINTMENTS_TABLE,

    WELCOME_MESSAGE, PERSONALIZED_ARTICLES, RECENT_ANNOUNCEMENTS

}